const questionsEasy = [
  {
    category: "I kto to mówi?",
    que: '"Być albo nie być" zastanawiał się bohater: ',
    odpA: "dramatu Szekspira",
    odpB: "powieści Tołstoja",
    odpC: "poematu Byrona",
    odpD: "piosenki The Beatles",
    correctAns: "dramatu Szekspira",
  },
  {
    category: "I kto to mówi?",
    que: "Szlachetne zdrowie, nikt się nie dowie jako smakujesz, aż się zepsujesz - to słowa:",
    odpA: "Konstantego Ildefonsa Gałczyńskiego",
    odpB: "Adama Mickiewicza",
    odpC: "Mikołaja Reja",
    odpD: "Jana Kochanowskiego",
    correctAns: "Konstantego Ildefonsa Gałczyńskiego",
  },
  {
    category: "Indie",
    que: "Głowę jakiego zwierzęcia ma Ganeśa, jedno z bóstw panteonu hinduskiego",
    odpA: "węża",
    odpB: "orła",
    odpC: "słonia",
    odpD: "Lwa",
    correctAns: "słonia",
  },
  {
    category: "Imiona",
    que: "Które z tych imion nosili najczęściej władcy Polski?",
    odpA: "Bolesław",
    odpB: "Zygmunt",
    odpC: "Władysław",
    odpD: "Jan",
    correctAns: "Władysław",
  },
  {
    category: "Kolęda",
    que: "Ulubioną kolędą Polaków, wg Polskiego Radia, jest: ",
    odpA: "Bóg się rodzi",
    odpB: "Lulajże, Jezuniu",
    odpC: "Wśród nocnej ciszy",
    odpD: "Cicha noc",
    correctAns: "Cicha noc",
  },
  {
    category: "kolory",
    que: "Jaki kolor przeważa na banknocie 20 euro?",
    odpA: "szary",
    odpB: "zielony",
    odpC: "żółty",
    odpD: "niebieski",
    correctAns: "żółty",
  },
  {
    category: "agent",
    que: "Który z wymienionych aktorów nigdy nie zagrał agenta Bonda, James Bonda",
    odpA: "Jack Nicholson",
    odpB: "Pierce Brosnan",
    odpC: "Sean Connery",
    odpD: "Daniel Craig",
    correctAns: "Daniel Craig",
  },
  {
    category: "aktorskie rody",
    que: "Który z przedstawicieli aktorskiego rodu Damięckich urodził się najwcześniej",
    odpA: "Maciej",
    odpB: "Mateusz",
    odpC: "Damian",
    odpD: "Dobiesław",
    correctAns: "Maciej",
  },
  {
    category: "gry i zabawy",
    que: "W którą z tych gier komputerowych mogliśmy zagrać najwcześniej?",
    odpA: "Tetris",
    odpB: "Mario",
    odpC: "Pac-man",
    odpD: "Prince of persia",
    correctAns: "Pac-man",
  },
  {
    category: "Gry planszowe",
    que: "Która z tych liter w tekstach pisanych po polsku występuje najrzadziej?",
    odpA: "ć",
    odpB: "ą",
    odpC: "ź",
    odpD: "e",
    correctAns: "ź",
  },
  {
    category: "boisko",
    que: "Boisko do piłki nożnej do rozgrywania meczów międzynarodowych poinno mieć wymiary:",
    odpA: "30m na 10m",
    odpB: "45m na 12m",
    odpC: "105m na 68m",
    odpD: "300m na 150m",
    correctAns: "300m na 150m",
  },
  {
    category: "boks",
    que: 'Pierwszym w historii polskim bokserem, który zdobył pas mistrza świata, przyznawany przez magazyn "The Ring", był:',
    odpA: "Andrzej Gołota",
    odpB: "Jerzy Kulej",
    odpC: "Przemysław Saleta",
    odpD: "Tomasz Adamek",
    correctAns: "Przemysław Saleta",
  },
  {},
];
